### ISSUE TITLE
Hip tracking

### ISSUE THREAD

**Issue by vrchatp** [TheNexusAvenger/Enigma#12]
At the moment there seems to only be support for right and left foot. Would hip tracking be possible as well?

**Comment by TheNexusAvenger** [comment]
This should have been an issue for Nexus VR Character Model instead, as Enigma does support those trackers. Nexus VR Character Model has no plans to support them. In V2 (current, soon-to-be-deprecated), the math to get it working beyond what I know. In V3 (coming eventually), there is no clear way to support them since that type of character control is being passed off to Roblox.
