### ISSUE TITLE
Is it supposed to be super laggy?

### ISSUE THREAD

**Issue by Spacanity** [TheNexusAvenger/Enigma#6]
Just wondering if i'm doing something wrong or if the trackers are supposed to be super laggy in-game.

**Comment by TheNexusAvenger** [comment]
The odds are likely because the clipboard is an I/O-heavy system that depends heavily on the application (Roblox), and it isn't super fast. However, some games do lag more than others. 1 game I won't name went <30 FPS with it running, and my guess it is due to key input handling. There is nothing that Enigma can do to solve it.

**Comment by Spacanity** [comment]
The game and everything works fine, running 60 fps. however the feet travel at about 3 fps i wanna say when moving the trackers

**Comment by TheNexusAvenger** [comment]
Can you provide a video of this, and state which trackers you are using?
